image: node:22.14.0

before_script:
  - npm ci --legacy-peer-deps

pages:
  stage: deploy
  script:
    - npm run build:gitlab
    - mv out-gitlab public
  artifacts:
    paths:
      - public
  only:
    - main
    - master
